// This file was generated by qlalr - DO NOT EDIT!

/*******************************************************************

Part of the Fritzing project - http://fritzing.org
Copyright (c) 2007-08 Fritzing

Fritzing is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Fritzing is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Fritzing.  If not, see <http://www.gnu.org/licenses/>.

********************************************************************

$Revision: 3442 $:
$Author: cohen@irascible.com $:
$Date: 2009-09-10 04:49:21 +0200 (Do, 10. Sep 2009) $

********************************************************************/

#ifndef SVGPATHPARSER_H
#define SVGPATHPARSER_H

#include <QVariant>
#include <QVector>
#include "svgpathgrammar_p.h"

class SVGPathLexer;

class SVGPathParser: public SVGPathGrammar
{
public:
    SVGPathParser();
    ~SVGPathParser();

    bool parse(SVGPathLexer *lexer);
    QVector<QVariant> & symStack();
    QString errorMessage() const;
    QVariant result() const;

private:
    void reallocateStack();
    int m_tos;
    QVector<int> m_stateStack;
    QVector<QVariant> m_symStack;
    QString m_errorMessage;
    QVariant m_result;
};

#endif // SVGPATHPARSER_H
