name: forgeedu-sync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: https://forge.apps.education.fr/canetsebastien/blocklyarduino-in-fritzing-app
        target-username: canetsebastien
        target-token: ${{ secrets.GITLAB_TOKEN }}
